# Generated by Django 3.1.3 on 2020-11-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
